kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: melroute 
  namespace: mqdr
spec:
  host: tls.chl.mq.ibm.com
  to:
    kind: Service
    name: melqm-ibm-mq 
  port:
    targetPort: 1414
  tls:
    termination: passthrough
