apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq1
  namespace: mq
spec:
  securityContext:
    supplementalGroups: [65534] # Change to 99 for clusters with RHEL7 or earlier worker nodes
  mqDashboard: true
  license:
    accept: true
    #license: L-APIG-CAUEBE
    license: L-RJON-CD3JKX
    metric: VirtualProcessorCore
    use: NonProduction
  queueManager:
    imagePullPolicy: Always
    storage:
      defaultClass: ibmc-block-gold
      persistedData:
        class: ibmc-file-gold-gid
        enabled: true
        type: persistent-claim
      queueManager:
        type: persistent-claim
      recoveryLogs:
        class: ibmc-file-gold-gid
        enabled: true
        type: persistent-claim
    availability:
      type: MultiInstance
      #type: SingleInstance
      #type: NativeHA
    metrics:
      enabled: true
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: '1'
        memory: 2Gi
    name: QM1
    mqsc:
    - configMap:
        name: mq1-mqsc
        items:
        - ivt.mqsc
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.3.1.0-r1
  web:
    enabled: true
  pki:
    keys:
      - name: label1
        secret:
          secretName: mq1key
          items:
            - tls.key
            - tls.crt
    trust:
      - name: trust1
        secret:
          secretName: tls-eris-trust
          items:
            - CSQ9.crt
  imagePullSecrets:
    - name: ibm-entitlement-key
