apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: sydqm
  annotations:
    com.ibm.mq/write-defaults-spec: 'false'
  namespace: mq
spec:
  license:
    accept: true
    license: L-QYVA-B365MB
    use: Production
  web:
    enabled: false
  pki:
    keys:
      - name: label1
        secret:
          secretName: mqkey
          items:
            - tls.key
            - tls.crt
  queueManager:
    name: QM1
    mqsc:
    - configMap:
        name: mq1-mqsc
        items:
        - ivt.mqsc
    ini:
    - configMap:
        name: mq1-mqsc
        items:
        - mq.ini
    availability:
      nativeHAGroups:
        local:
          tls:
            key:
              secretName: sydkey
          name: sydney
          role: Live
        remotes:
          - addresses:
              - melqm-ibm-mq.mqdr.svc
            trust:
              - secret:
                  secretName: tls-mel
            name: melbourne
            enabled: true
      type: NativeHA
    storage:
      queueManager:
        type: persistent-claim
      defaultClass: ocs-external-storagecluster-cephfs
  version: 9.4.2.0-r1
