kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sydroute 
  namespace: mq 
spec:
  host: tls1.chl.mq.ibm.com
  to:
    kind: Service
    name: sydqm-ibm-mq 
  port:
    targetPort: 1414
  tls:
    termination: passthrough
